### ISSUE TITLE
zig version problem  0.9.1, master? 

### ISSUE THREAD

**Issue by sukoi26** [Hejsil/zig-nuklear#2]
i try to use ZIG master to compile   but seems sources define for  version < 0.9.  Do you will  upgrade to new version of ZIG?

i try some change:
  build.zig        defineCMacros   to take separate name and value arugments.
  nuklear.zig    c_void   by anyopaque 

but this message let me  without solution 
:~/dvp/zig-nuklear$ zig build
./zig-cache/o/315006ea2dba4bdf5300abd4bceeb54c/cimport.zig:189:5: error: expected token '}', found 'null'
    null: struct_nk_draw_null_texture,

related:
struct nk_draw_null_texture {
    nk_handle texture; /* texture handle to a texture with a white pixel */
    struct nk_vec2 uv; /* coordinates to a white pixel in the texture  */
};

thank you for this work on this library.

**Comment by sukoi26** [comment]
add info 
![image](https://user-images.githubusercontent.com/23014567/161382725-d0418822-5aaa-4865-89ed-5472e82fcb3e.png)

**Comment by Hejsil** [comment]
I don't really use this lib much myself anymore, so I haven't really done much on it. I'll see if I can do the bare minimum to get it up and running for zig master.

The problem you hit seems like a translate-c bug. We can work around this.

**Comment by Hejsil** [comment]
Just updated to compile with newest zig 7b5975b24216855e2c300ad4c9d4dc5800802086

**Comment by sukoi26** [comment]
thanks for the responsiveness
i pull and the result still problem  "null"  translation
![image](https://user-images.githubusercontent.com/23014567/161384441-433498cc-9b90-4f39-a73e-4b22030a1c3d.png)

**Comment by Hejsil** [comment]
Huh. I guess the cache screwed me over. I'll have a look

**Comment by Hejsil** [comment]
Try again 0044703

**Comment by sukoi26** [comment]
Good! but  the origin file header need to be changed ..
i will make more test, 
new to the Zig language, I'm also testing NUKLEAR, I'm looking for a library to make a small graphical interface

i close the issue

th+

the result 
![image](https://user-images.githubusercontent.com/23014567/161388331-821bbe53-5da7-4b19-8822-73bbae21d936.png)
