### ISSUE TITLE
how update  the nuklear.h  for the lib ?

### ISSUE THREAD

**Issue by sukoi26** [Hejsil/zig-nuklear#3]
It is more a question of the way to do  as i note the  origin file header is at  4.9.6 version 
![image](https://user-images.githubusercontent.com/23014567/161389904-98d13f88-a557-4c93-a2d7-1c56df2a9222.png)
i note also lot of change in the  origin file  but do you a list ,document of specific changes for Zig  import  or i need check  each  ....
 as
![image](https://user-images.githubusercontent.com/23014567/161390267-b3fd7e68-9cea-43af-b8a1-381e9652bcee.png)

**Comment by Hejsil** [comment]
These bindings target a fork I have that makes Nuklear more friendly for slices. It is a big change located [here](https://github.com/Hejsil/Nuklear-1/tree/null-termination-be-gone). I have not updated this in a while though

**Comment by sukoi26** [comment]
I will try while learning ZIG to understand the modifications compared to the original source. Indeed the slice is a difference.
